### ISSUE TITLE
usage questions

### ISSUE THREAD

**Issue by pingit** [christiangoltz/shaape#7]
I'm still reading through the document, but there seems to be some of issues immediately seen here:
1) how to "escape" some of the text strings to make them being displayed literally?
2) some of the ====> line disapeared, and only > got displayed as arrow
3) my dotted lines (...) got lost
4) if the gradients consumed too much cpu, can we disable it but just use shadows?
5) all braces "()" are rendered to some curly crossing lines, how to escape them and get a literal () ?

**Comment by christiangoltz** [comment]
1) text that contains special characters needs to be surrouned by single quotes, e.g. 'foo<>bar' (I also added a section describing this to the README on the development branch)

2) the equals sign (=) is not a valid identifier for a line, see section Drawing->Lines in the README, the basic identifiers for lines are - | / . If you want a thicker line, have a look into the README at Drawing->Styles. I already thought about adding = as an identifier for a line, but because there is no vertical equivalent, I will not add it to shaape.

3) there is nothing like dots for lines, you will need to redraw them with either + \* or the normal line characters. Can you explain what you need the dots for? Should it show something like a thinner or dotted line? If there is a plausible reason for the dotted lines, then I would add the dots to the shaape grammar.

4) gradients dont consume much cpu, because they are rendered with cairo. Shadows do consume a lot of cpu because they are blurred manually via numpy. There is currently no way to disable the shadow layer blurring for the png backend. If you want, I can add a commandline option and also a filter option for the asciidoc filter to completely turn off the shadows, that should give you some speed boost.

5) the braces should be quoted: '()'

I took a look at your ascii source diagram, it looks quite complex and is packed with a lot information. The idea behind shaape is, that both, the ascii source and the produced image stay readable. So to stay compatible with shaape you would need to rewrite some parts of the diagram, because shaape doesnt support all the types of drawing that you used, but this will also help you to make the source itself more readable. You are welcome to ask here if you have problems transforming specific elements into shaape syntax.

**Comment by pinggit** [comment]
1) this looks good to know.
and still, I'm thinking a global option to "disable" charactor/string rendering will be nice to have (e.g.: aafigure -T option)

2) even if there is no vertical equivalent, can we still have it in horizontal :) ?
I think ignoring '=' to mean sth is a waste... it can either mean a "thick/bold" line, or a double line, all with configurable values. if you are looking for a vertical equivalent, how about double bar?

||
||
||
||
||

3) I just read this the shaape way of doing the work:

## ["shaape",scaling="0.7"]

a------
b------
c------
d------
options:
- ".*" : {text : [[0,0,0,0]], fill: [3]}
- "a" : {fill : [solid]}
- "b" : {fill : [dotted]}
- "c" : {fill : [dashed]}
- "d" : {fill : [dash-dotted]}

the options are great, in terms of customization. but immediately I think it break the "rule" of an "ascii-art" -- the original text graph need to be looking as close as what it meant, but charactors doesn't looks a line in any way, right?
another drawback is , if you use charactor as part of line element, how do you diff them with the real charactors? and this might make the "diable any fills/effects globally" feature harder to implement? look at aafigure project, they have a nice feature called "--textual, or -T" to horizontally disable the "fill".

my point is that we should not use normal charactors as port of the drawing, as possbile as we can, unless have to. (then at least we have a readable figure that conveys the original sense if we don't have a great tool to conver it :D  ) but this is just my point. 

I think its a pity to ignore dot, unless you are going to use it anywhere else.

in many scenarios I need another line to circle in another way other than the normal line, just to demonstrate some logical "range" or "scope" of the objects, [e.g. I want to show the reader that: element A and B should be in one cloud (a normal line circle), but actually B and C are actually physically in one place (a dotted circle), sth like that]

I think you are right that my diagram is too complex for an ascii-art, it still might confuses people. I'll try modify it in shaape way and see if I can make it simpler in asciiart, and shaape-compatible as a learning effort.

thanks!

**Comment by pinggit** [comment]
another quitions:
6) how to make the diagonal curve looks smooth?

## currently with this I couldn't get a old line:

 \  
  -  
    \L1  
     \  
      -  
        \  
         \  

##           -

I tried change "-" to "*" or "+", still no improve.

**Comment by christiangoltz** [comment]
1) there is nothing like a fill detection algorithm in shaape like in aafigure, so there cannot be an equivalent for the -T option here. I admit maybe the regular expression that searches for the words in the drawing only matches the minimum amount of letters that we can be sure are not part of the lines of the drawing, thats why they need to be quoted. Maybe I just didnt understand clearly what you mean ^^
2) double bar wont work, because || takes the space of 2 ascii characters and thus has to take the space of these in the rendered image too, this would make the line too thick. The other drawback would be that we couldnt have 2 lines directly next to each other any more. However I will add the equal sign for horizontal thick lines.
3) the characters are not part of the line, this one was just an example, that uses a trick to hide the characters. The normal way I would encourage you to go is to draw your line, write a good name next to it and assign a style to the name, some small example:

```
net_flow
------------------------>

options:
- "net_flow" : {fill : [dashed, red, 3]}
```

This will draw the dashed red and thick line with an arrow and also the name net_flow above the line. So no characters are removed and the rendered image stays consistent to the ascii source as far as possible (there is no dashing, color and thickness in the source, but at least line, arrow and text are there). The name does not have to be above the line, it is sufficient if one of its letters has a distance lower or equal to 1.5 letters, so you can put it at the front, at the end or anywhere between near the line. A line can have multiple names and their styles are applied in the order that they are found in the options section.

In the example from the README that you provided in your comment above, I use the first option with the .\* to hide all text in the diagram to create a prettier image in the README, but as you already said this produces a rendering that is missing the characters. I wouldnt advise anyone to use this trick, but it can be handy to have if you need it.

I will add the dots with a default style that creates a dotted line or frame if the polygon is closed. The dotted line may be a nice way to draw lines in the ascii source that draw less of the viewers attentions than a normal line.

The A,B,C example that you mentioned, could look something like this in the current implementation:

```
+---------------------+
| cloud   +---------+ |
| +-----+ | +-----+ | |
| | 'A' | | | 'B' | | |
| +-----+ | +-----+ | |
+---------------------+
          |         |
          | +-----+ |
          | | 'C' | |
          | +-----+ |
          | physical|
          | boundary|
          +---------+

options:
- "cloud" : {fill:[[0.5, 0.5, 0.5, 0.5]]}
- "physical" : {fill:[green], frame:[dotted]}
```

This renders:
![ex shaape](https://f.cloud.github.com/assets/2478085/441464/df766328-b11a-11e2-88c9-c801d9ea76d6.png)

**Comment by christiangoltz** [comment]
6) The naturally supported types for diagonal lines are / and . They can be connected to other line elements via a + junction. The + needs to be in the direction where the diagonal line is pointing. For the / either to the upper right or lower left, for the \ either to the upper left or the lower right, example:

```
 \              /
  ++          ++
    \        /
     ++    ++
       \  /
```

Unfortunately this renders a "stairy" look:

![ex2 shaape](https://f.cloud.github.com/assets/2478085/441481/1b463dd2-b11c-11e2-99f9-acdb70dadf1b.png)

I took several attempts to somehow smooth such lines, but it is algorithmically complex and doesn't work as expected for most cases so I dropped these attempts. As so often it is simply better not to use any features that cannot be expressed in the ascii source code, smooth diagonal lines without stairs that have a different degree than the default / and \ are just not possible in the source ascii, so they are not possible in the rendered image too... well unless someone comes up with a good algorithm to solve this ;)

**Comment by pingit** [comment]
3) dot line: 

quoted from you:
"The dotted line may be a nice way to draw lines in the ascii source that draw less of the viewers attentions than a normal line."
-- this is exact effect that I wanted to have in my picture, to create some different levels of emphasis in one picture, so back in my example of A,B&C, I hope people will notice immediately that B&C is in a physical location , which is mainly what they wanted to read, but at the same time, have some slighter signs showing that A&B are also in the same cloud --- and those signs need to be slighter enough to not confuse the main meaning that the picture is delieverying: B&C is a in one box.

anyway, I'm testing your solution (the net_flow example).

6) diagonal lines
got it, that's good enough (if there is no other simple better way). b.t.w, can't we borrow the ( or ) here to make it a little bit more smooth?

new issues:
7) can shaape support stdin  as filename? it's quite handy in vim to hook that stdin.

8) document
via talking to you, I understand better about some subtle rules that you mentioned in your email , but might not in the readme...I'm taking notes here.

"
The name does not have to be above the line, it is sufficient if one of its letters has a distance lower or equal to 1.5 letters, so you can put it at the front, at the end or anywhere between near the line. A line can have multiple names and their styles are applied in the order that they are found in the options section"

**Comment by pingit** [comment]
8) Bezier curves
I'm study shaape via my "complex" asciiart here:
http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape
I think if I can make it good, pretty much I can use it in most other scenarios.

if you look at it, in the top there are 2 filled clouds (t1 r2) and (c2 r9), basically they looks fine, but there are some tiny/ugly extra circles attached there which, I don't understand why and how to avoid those?

**Comment by pingit** [comment]
9) turn off "filling"
and, I tried this to turn off the filling:

```
+-----------------+
|MX2  NS          |
|                 |
+-----------------+


options:
- "NS" : {fill : [no-shadow]}
```

but it doesn't work as expected...

**Comment by pingit** [comment]
9) turn off "filling"
and, I tried this to turn off the filling:

+-----------------+
|MX2  NS          |
|                 |
+-----------------+

options:
- "NS" : {fill : [no-shadow]}

but it doesn't work as expected...

just realized via continuing my doc reading, so shadow is not a "fill" :) , but here might be a minor doc bug:

```
                   +---->
  +------+        /         
  | box1 |  -----+ 
  +------+    line1    
```

options:
- "boxname[0-9]": {fill: [red, flat], frame: [blue, dashed], no-shadow}

should be "box[0-9], right?

**Comment by christiangoltz** [comment]
3) dotted lines: I just finished the implementation for the dotted lines, should work, you can find the example that I used for testing here: https://github.com/christiangoltz/shaape/blob/develop/shaape/tests/input/feature_dots.shaape
The result looks like this: https://github.com/christiangoltz/shaape/raw/develop/shaape/tests/expected_images/feature_dots.shaape.png

So this should work on the develop branch now(it is not pushed to the master release branch). I hope it fits your needs, if you have any problem with the dotted lines, just tell me.

6) we can't borrow the ( and ) I think because I already used them for special crossings like

```
 |
-(-
 |
```

I also cannot exactly imagine how the resulting image should look like, maybe you can make an example graphic with an image editor to show me, if this is important for you.

7) stdin is supported, shaape --help prints something like:

```
usage: shaape [-h] [-o OUTFILE] [--hash] [-t {png,svg,pdf,eps}] [-s SCALE]
              [--width WIDTH] [--height HEIGHT]
              infile

positional arguments:
  infile                input file, can be - if the input comes from stdin
```

8) if you feel that something is missing in the README, you may also just add it yourself and create a pull request via github, as I am the sole developer of this project and I put most of the time into testing and implementation, the README is always the last thing I write and for sure is not very good ^^

I also took a look at your example again, the tiny extra circles in the bezier curve circles come from patterns like:

```
**
 *
```

This basically looks like a little triangle for shaape. However I decided to not support these little triangles and to remove them, because they dont look exactly like triangles in the source code too, this was basically a problem for the dotted lines too, so I removed the small triangles for *,+ and . You can try to convert your ascii source with the current development version of shaape again and hopefully these little circles are gone.

If you still use the master branch, then just use

```
*
 *
```

for the corners instead the 3 stars.

9) this is no real error in the README because both examples dont really belong together, but I changed it to your suggestion, so the reader doesn't get confused.

To turn off the fill of a polygon you would use:

```
options:
- "NS" : {fill : [[0, 0, 0, 0]]}
```

The four zeros are the RGBA colors for the fill. To make this easier I added a color definition in the development branch for this, which is called 'empty'. You can use it the same way as red, green and blue:

```
options:
- "NS" : {fill : [empty]}
```

You can find a lot more examples for styles inside the test case inputs here: https://github.com/christiangoltz/shaape/tree/develop/shaape/tests/input

**Comment by pinggit** [comment]
hi:

I'm new to git...how do I get the new version?
I did this:

ping@640g-laptop:~/shaape$ ls
asciidoc-filter  bin  CHANGELOG  LICENSE  Makefile  README  README.html 
  setup.py  shaape
ping@640g-laptop:~/shaape$ git pull
X11 forwarding request failed on channel 0
remote: Counting objects: 87, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 59 (delta 36), reused 47 (delta 24)
Unpacking objects: 100% (59/59), done.
 From github.com:christiangoltz/shaape
    4be8096..58c5501  develop    -> origin/develop
- [new branch]      feature-dotted-lines -> origin/feature-dotted-lines
  Already up-to-date.

now is this the new version?

~/shaape/bin/shaape

thanks!

**Comment by christiangoltz** [comment]
you normally use

```
git pull
```

to update your repository from the remote repository. You did this and everything went fine. Now you need to change the current branch to the develop branch:

```
git checkout develop
```

You can use

```
git status
```

To check which branch is currently checked out. I guess you where on the master branch before, which contains the latest stable release but not the current fixes.

You can run

```
sudo make install
```

to install shaape into your system and

```
sudo make install-filter
```

if you also want to install the asciidoc filter plugin.

**Comment by pingit** [comment]
10) about the yaml syntax in shaape:

```
options:
 - ".*": {fill: [red, flat], frame: [blue, dashed], no-shadow}
 - "boxname[0-9]": {fill: [blue]}
```

for the above example, I can't fully understand these:

```
- ".*": {fill: [red, flat], frame: [blue, dashed]}, no-shadow}
```

so for me that means: 
- for all IDs (.*)
  - fill it with color red, what is "flat" (I don't see explanations in readme)?
  - use blue dashed line
  - no shadow for the fill, but it looks there is no "style" for this "no-shadow" value to apply to, and the correct syntax should be like this, right?
    
    "._": {fill: [red, flat], frame: [blue, dashed]}, fill: [no-shadow]}
    or
    "._": {fill: [red, flat, no-shadow], frame: [blue, dashed]}, }

I'm confused a bit about the yaml syntax here.
thanks!

**Comment by christiangoltz** [comment]
10) Well this time it really is an error in the README:
First of all, flat was removed. In the first versions of shaape, I used "flat" and "gradient" to indicate the visual style if the fill. I removed them, when I introduced fully customizable gradients. To use a fill with just one color (the former flat), you now simply only provide one color:

```
- ".*": {fill: [red]}
```

This will fill you boxes red. For gradients you simply specify more than one color:

```
- ".*": {fill: [red, green, blue]}
```

So just forget about the flat, I removed it from the README now.

You are also right with the no-shadow, again an error in the README, it should be:

```
- ".*": {fill: [red, no-shadow], frame: [blue, dashed]}
```

I fixed this in the README too.

At the moment, no-shadow is only supported for "fill" and for "text". This may become a problem if you want to draw empty box but also want the frame of the empty box to have a shadow.

I am also not completely happy with the yaml syntax, but I dont know of any other easy-to-learn lightweight language that I could use for this purpose, maybe pure python would be some way. xml would be far to overloaded with metasymbols and jason is not as readable as yaml.

**Comment by pinggit** [comment]
I tried my best to learn the rules and then apply what I learned to make my topology looks the best , but still had some issue, I think its best to show you the source and result so you will know what is my current difficulties:

http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape/

let me "renumber" the issues we talked previously.
1. still no equal sign support, so only arrows got displays, no thick horizontal lines leading the arrow.

please ignore, this looks supported now, perfect!
1. I want to selectively empty some fill. so this is what I desired:
   - "L1" : {fill : [empty]}
   - "L2" : {fill : [empty]}

but looking at the final graph, only one part in the middle have the right result (no fill), the right part of it still no change, but they do have the IDs containing of "L2", right?
- workaround of it:
  I tried to change:
  - "L2" : {fill : [empty]}

to

```
- ".*" : {fill : [empty]}
```

I know this is not what I wanted, but just to test this "empty" out, but it looks not only the fills, but also some lines disappears -- it all looks like , the empty doesn't only work on "fill", but also on "frame" (which means "lines" to me). but shouldn't only "fill" got applied with "empty" values?

My understanding, we are having the ID:"style:values" pairs, the values should only work on the style that it follows, even if the ID is ".*", or I'm wrong maybe?
- I know one other simpler workaround is to leave it open, like what I did for the left part of the block. but obviously this is not a ideal solution.

**Comment by pinggit** [comment]
3)  where is the target image path?
I did a LOT of tests on this issue...

by default I got this:

```
IOError: error while writing to output stream
asciidoc: WARNING: <stdin>: line 2553: filter non-zero exit code: shaape -o "/usr/local/etc/asciidoc/vim-jtac-work__1.png" --hash  --scale 0.5  -: returned 1
asciidoc: WARNING: <stdin>: line 2553: no output from filter: shaape -o "/usr/local/etc/asciidoc/vim-jtac-work__1.png" --hash  --scale 0.5  -
sh: /usr/local/etc/asciidoc/vim-jtac-work__1.png: No such file or directory
```

except "scaling", I also tested "target" options, which is hidden now (not in readme)

```
["shaape", scaling="0.5", target="abc"]
```

now shaape is going to genenate the image into this:

```
/usr/local/etc/asciidoc/abc/vim-jtac-work__1.png
```

so basically the result shows that it's the same as asciidoc imagesdir attribute. 

but I don't want to write into  system folder `/usr/local/etc/asciidoc/`, how shall I control this?

4)  shaape-filter.conf file

because of question3, I tried to understand the filter config here:

```
ping@640g-laptop:~$ cd .asciidoc/filters/shaape/
ping@640g-laptop:~/.asciidoc/filters/shaape$ ls
shaape-filter.conf
ping@640g-laptop:~/.asciidoc/filters/shaape$ cat shaape-filter.conf 
#
# AsciiDoc shaape filter configuration file.
#
[shaape-filter-style]
ifndef::data-uri[]
shaape-style=template="shaape-block",subs=(),posattrs=("style","target"),filter='shaape -o "{outdir={indir}}/{imagesdir=}{imagesdir?/}{target}" --hash {scaling? --scale {scaling}} {width? --width {width}} {height? --height {height}}-'
endif::data-uri[]
ifdef::data-uri[]
shaape-style=template="shaape-block",subs=(),posattrs=("style","target"),filter='shaape -o "{indir={outdir}}/{imagesdir=}{imagesdir?/}{target}" --hash {scaling? --scale {scaling}} {width? --width {width}} {height? --height {height}}-'
endif::data-uri[]

[blockdef-listing]
template::[shaape-filter-style]

[paradef-default]
template::[shaape-filter-style]

[shaape-block]
template::[filter-image-blockmacro]
```

I admit I don't understand the syntax here -- I never write any asciidoc filters myself, but I believe this is where the issue is --- I have to customize it a bit to fit my own need, bottom line is don't generate the target file into system file that requires a root login. can you brief me how does the above config file works and how to change it, say, make it always generate the image file into the same folder as the asciidoc output file place?

**Comment by pinggit** [comment]
5) what's the definition different between ID: "_line_" and style: "frame" ?

by some testing it looks "frame" means only for lines in a closed objects?

how come a _line_ can also have a "fill" style in the following example? 

```
- "_line_": {fill:[[0.1, 0.1, 0.1], solid, 2]}
```

I think the document need to be enhanced to make it more concrete and clear...

**Comment by pinggit** [comment]
while I'm continuing my usage practice and study of shaape, I run into another small, but annoying issue.

in a lot of cases, I need to have some text in the polygens , and the text need to include:

6) about ID
- a single quote
  
  +-------------------+
  |make sure it's good|
  +-------------------+
- a dot 
  
  +-------------------+
  |1. power it off    |
  |2. power it on     |
  +-------------------+
  
  rewrite . with '.' works:
  +-------------------+
  |1'.' power it off    |
  |2'.' power it on     |
  +-------------------+
  
   but couldn't we use \ as an escape , instead of two ' , to make it simpler?
- ? mark does't get displayed

**Comment by christiangoltz** [comment]
1. equal signs should give you thick lines now, see https://github.com/christiangoltz/shaape/blob/develop/shaape/tests/input/feature_thick_lines.shaape for an example.

I inserted this today.
1. is this fill problem solved or does it still exist?

3 + 4. the target path depends on wether you use the data-uri option with asciidoc. Without the data-uri option, the images are generated into the path where the output file of asciidoc is put into. With the data-uri option the images are generated into some asciidoc dir. I am not completely sure why this is necessary, but I had a user, who reported problems when the images were generated into the same path as the output when using the data-uri option and this user send me his working solution as this filter config. I don't completely understand the magic in the filter config, so I will do some research in this area.
1. "frame" means the enclosing line of a closed shape. So in general the border of a polygon. "fill" always directly means the object that matches the given name, so if you have got a polygon that contains the name "abc" then fill means the fill of the polygon and if you have a line that has "abc" written next to it then fill means the fill of the line.
   "_line_" is a special name. It matches all lines, no matter wether they have a name or not. so
   - "_line_" : { fill : [red]}

would change the color of all lines to red. "frame" wouldnt change anything if applied to a line. Maybe you can make a suggestion how you would explain this yourself or if you would like to change anything on that.
1. Having a backslash as an escape sequence always looked like a bad idea for me, imagine this example:
   
   1. power it off------->

There are two possibilites to render this:
1. you render
   
   1 . power it off------->
   (blank space between 1 and .)
2. you render
   1. power it off -------->
      (blank space between "off" and the arrow behind)

There are maybe even more possibilities that could be considered as correct by some users. So the basic problem here is, that every character gets rendered into its own place in the resulting image in a monospace manner. So there is no easy and consistent way to render 2 characters from the source file to one character in the resulting image without leaving some space somewhere else. I think it would be too hard to decide where to place the space and I dont want to lose the monospacing, because monospace has the major advantage that you can exactly align your text in the source file, e.g.

```
abcdefgh
   1234566
```

Would render the 2 directly below the d, exactly like in the source file.
The only consistent way to have special characters and to keep the monospace with its source/result consistency seems. I have one essential advice for you when using special characters: always quote the whole string:

```
+-------------------+
|'1. power it off' |
|'2. power it on' |
+-------------------+
```

This way the name of the polygon would also include the whole string and you can match it in the options section as a whole string.

Currently there is no way to display a single quote and it may even not be possible to have this. Would a backquote be a possible alternative?

Does the ? work if you quote it?

I will take a look if I maybe can active all the special characters that are not used for drawing lines and stuff, so you wouldnt need to quote % for example.

**Comment by pinggit** [comment]
I don't like markdown list numbering system :)

to summarize (using [my graph](http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape/) as examples):
1. equal sign
   yes it looks supported now. as I can see in my graph. thanks!
2. the selectively "fill" issue of my graph
   no I still don't fully understand, how to just fill some of polygons. I know I need to use "style ID", and that's what I did in [my asciiart source file](http://pinggit.github.io/docs/asciiart-network-topology.txt)
   
   ```
   #this works
   - "L1" : {fill : [empty]}
   
   #this doesn't work, don't know why
   #- "L2" : {fill : [empty]}
   ```
   
   and you can look at the [rendered picture](http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape/) - some are still not empty. 
3. so this hidden `target` is the same as `imagesdir` attribute in asciidoc , right?
   
   ["shaape", scaling="0.5", target="abc"]
4. for the asciidoc filter, I now use this workaround:
   
   I changed this,
   
   ifdef::data-uri[]
   #shaape-style=template="shaape-block",subs=(),posattrs=("style","target"),filter='shaape -o "{indir={outdir}}/{imagesdir=}{imagesdir?/}{target}" --hash {scaling? --scale {scaling}} {width? --width {width}} {height? --height {height}}-'
   
   to this:
   
   #ping:
   shaape-style=template="shaape-block",subs=(),posattrs=("style","target"),filter='shaape -o "{outdir={indir}}/{target}" --hash {scaling? --scale {scaling}} {width? --width {width}} {height? --height {height}}-'
   endif::data-uri[]
   
   and now with this command:
   
   asciidoc -v -a numbered -a toc2 -a toclevels=4 -a iconsdir=/home/ping/bin/asciidoc-8.6.8/images/icons -a icons -a imagesdir=/mnt/public_html/webdata/vim-jtac-work -a data-uri -o /mnt/smbwf-sam/home/public_html/webdata/vim-jtac-work/vim-jtac-work.html -a leveloffset=0@  -b html5 vim-jtac-work.txt
   
   I got the desired result.
   
   I haven't fully figured out why though...but this is my current best practice to combine the data-uri with shaape.
5. `frame` and `line`: so in short, shall I say, `frame` is a "non-fillable" line (its color is controlled by the shape that it closes) , and a line is a fillable line, correct me again if I'm wrong. 
6. the special charactors display issue:
   I don't fully get it yet, but I think you are right that I can always quote the whole text. and the question mark get displayed too if I quote it. the only thing now looks, there is no way to display a quote, maybe we can display a quote by two neighboring single quote?
   
   I don''t like it

for me the current deployment blocker, is just question 2 (selective fill control), if you have time, please advice based on [my asciiart source file](http://pinggit.github.io/docs/asciiart-network-topology.txt) and [rendered picture](http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape/). I'm been practice a lot based on it, and this is sth really I couldn't figure out ...

thanks!

**Comment by pinggit** [comment]
b.t.w, looking at your equal sign example [here](https://github.com/christiangoltz/shaape/blob/develop/shaape/tests/generated_images/feature_thick_lines.shaape.png), there is thing I'm not sure is an issue or not:
in the [source](https://github.com/christiangoltz/shaape/blob/develop/shaape/tests/input/feature_thick_lines.shaape), there is an unquoted A, functioning as an `style ID` here, or `style ref`,

```
    .  |   
 <==.==|==>A
    .  |    
 ==========--->
    .  |     

options:
 - "A" : { fill : [red]}
```

so per my current understanding, that A, shouldn't get displayed in the final picture, since it's only usage here is a reference to the style, and we don't really need an A there? or, preferably, there can be an option for this feature : to turn of the display of all unquoted non-drawing charactors in the asciiart, that solely be used as a reference to the lines/polygons ? just a thought...

**Comment by christiangoltz** [comment]
1. This was a bug in the software, I just happened to fix it now and it should work as expected in the latest development branch on git now. I took a further look at the comments in your example, the "c2" is not blue because you need to put the blue into brackets like this
   
   fill : [blue]

because the attribute that is associated to the fill key always is a list of values, this list even may contain no elements at all or like here only one element.
1. - 4. cant really answer on this, I didnt have any time to look at this problem.
2. both, frame and line are kind of fillable, but you are right when you say that the frame style is controlled by the shape that it encloses.
3. 2 neighboring quotes would at least be possible to parse for me, but again, it will look strange if you write
   
   don''t

for example, because there will be a space either at the first or second quote. Maybe a solution would be, that single quotes, that are enclosed by letters get rendered as text. In this case you could simply write "don't", but not "don' t". Another version would be to use either single or double quotes, so you could write

```
"don't"
```

if you want a single single quote or

```
'don"t'
```

if you want a single double quote.
1. the equal sign example works correct. All the text in the ascii source, no matter if quoted or not gets displayed. There is nothing like text that only works as a reference for the style. I know you already saw one of the examples in the readme, where the single letters are hidden. This is a complete different scenario, if you want to hide text from the final image, then you have to explicitly set its color to empty (Thats what I did in the Readme). However, hiding characters from your final image that are visible in the source file is not a good practice and shouldnt be used too often, because it results in heavy differences between source and generated image and I this is not what  I would like to achieve.

**Comment by pinggit** [comment]
hi, 
1. that's great progress!, now I got exactly what I wanted, as you can see from [here](http://pinggit.github.io/tech/2013/04/29/ascii-art-shaape/) 
2. about the displaying of single quote, I think you have a more considerable thought than me, please just put note once you finalized the solution so I can stick to it.
3. about the displaying of the style reference: I think I almost agree, in the spirit that asciiart source need better to reflect the rendered result as close as possible.
   but, there is one problem here: I'm sure people will constantly run into a case, that the graph itself is done and clean, but he just need a way to refer one of the subject in it instead of another, to do some special things on it. there is no other way to do it other than adding the referenceID, which, according to current implementation, will also be added into the rendered graph...just a simplest example here:
   
   ```
   -----------
   -----------
   -----------
   ```
   
   in the above file, I just need 3 lines there and I don't want to add anything else. 
   but I need to make the 1st line red, 2nd line blue, 3 line yellow and dotted, how do achieve that ?
   
   A-----------
   B-----------
   C-----------
   options: .....
   
   you might argue we can simple use some letters, but I'm sure in some places we don't need any extra things to make it more confusing, but instead we only rely on the color or line styles to show the differences of two subjects..
   
   my point is, the best solution, is to add one option knob, so people can decide whether they want to use the reference just as a non-visible reference, or, make it visible as well.
   
   just my 2c.

again, thanks for your great tool, I like it!

**Comment by pinggit** [comment]
one more question (let me know if I have too much stupid question for you :)  ):
4.. about the regex:

I don't see any description about the regex , but the examples show it does support ,for the style ID.
which flavor is it? perl/vim/shell?
I'd like to learn more detail specs about that...

**Comment by christiangoltz** [comment]
1. Shaape is no tool to just draw pretty graphics with plain text files. It is not it's main goal to give the users the ability to draw every image that they want, because there are better tools for that, simple pixel graphic editors would do that far better. The main goal is to draw diagrams with specific meanings. In this case an example like you suggested: 
   
   ---
   
   ---
   
   ---

would look like 3 completely equal lines in the source file. They just cannot look different in the rendered image, because this would completely change the meaning of the graphic. Imagine one user looking at the ascii source who sees 3 completely equal lines, thinking "well 3 equal lines" and another user looking at the rendered image, who sees a red, a yellow and a green line, thinking "looks like the flag of ghana".

However, the option knob you referred to is already there, you can always hide the text you write by setting the text color to empty:

```
a------
b------
c------
d------
options:
 - "a" : {fill : [solid], text : [[0,0,0,0]]}
 - "b" : {fill : [dotted], text : [[0,0,0,0]]}
 - "c" : {fill : [dashed]}
 - "d" : {fill : [dash-dotted]}
```

a and b will be hidden, all lines will look different, you should also be able to use "empty" instead of [0, 0, 0, 0].

Maybe lets just wait some time and see if there are more users, who want a more explicit functionality to hide the text, if there are more requests, I would rethink this stuff. At last this project is open source and whoever wants this feature could also implement it on his own.

You are always welcome to post your opinion about shaapes features, I hope to see some more drawings generated with shaape ;)
1. There are no stupid questions, this one is really missing in the Readme. I don´t know about all of these styles, but I guess it is like the perl style, you can get a good overview at http://docs.python.org/2/library/re.html

**Comment by pinggit** [comment]
hi chris,

do you know how to make the bottom two ++ connected to each other?

```
                          +---------+
                          |         |
                          |         |
                 FPC4     |         |
            +------------+|         |
  xe-4/3/0  |            ||         |
  ----------+            ||      lo0|
   ---->----+----->----->++>-*   ^  |
            +------------+|  |   |  |
                 FPC0     |  v   |  |
            +------------+|  |   ^  |
            |       <----++--*   |  |
            | si-0/0/0   ||      |  |
            |       >----++-->---*  |
            +------------+|         |
                          +---------+
```

**Comment by christiangoltz** [comment]
There are a lot of ++ in your diagram, can you simplify it or exactly say which ++ you mean and what you want to look it like? You can maybe also compile the image with shaape and mark the place in the created image.

**Comment by christiangoltz** [comment]
I guess this is dead.
